project:
  type: website

website:
  title: "Data guide"
  navbar:
    left:
      - icon: globe
        menu:
        - href: index.qmd
          text: Guide in English
        - href: spanish.qmd
          text: Guide in Spanish
    right:
      - href: https://www.jointdatacenter.org/venezuela-migration-report/
        text: Full report
      - href: https://www.jointdatacenter.org/venezuelan-migration-data/
        text: Data
      - href: https://www.jointdatacenter.org/
        text: Joint Data Center on Forced Displacement

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

