project:
  type: website

website:
  title: "Data tutorial"
  navbar:
    left:
      - href: https://www.jointdatacenter.org/venezuela-migration-report/
        text: Full report
      - href: https://www.jointdatacenter.org/venezuelan-migration-data/
        text: Data
      - href: https://www.jointdatacenter.org/
        text: JDC website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

